### PR TITLE
Filter events

### PR DESCRIPTION
**Pull request by dmitriy-uvin**

### CODE REVIEW

**Review by aussie-m-mike — CHANGES_REQUESTED** [review]
I guess better to use the scopes, to avoid get all the data from the DB and then filtering them. Please add to EventType entity, 
`public function eventsScheduled()
    {
        return $this->events()->scheduled();
    }`

and then use `$eventType->eventsScheduled->map(...)` Thanks.

**Comment by dmitriy-uvin** [comment]
Looks good. But I think that for us project it will not affect so much on our performance.

**Comment by aussie-m-mike** [comment]
That's not only about performance thing, if in future we need to remove any other status from the schedule list we will need change only scopeScheduled in EventEntity, but In this way we'll need to change in multiple places. :)

**Comment by dmitriy-uvin** [comment]
We have demo in one week, I don't think we will change status. :) But, your idea make sense. I like it.

**Comment by aussie-m-mike** [comment]
You need only change one line code in api/app/Actions/AvailabilityService/ProcessUnavailableTimeAction.php and add one method in EventType entity, all other stuff already in place. ;)

**Review by aLLeXUs — APPROVED** [review]

**Pull request merged**
